src/app/components/table/collaboration-table/collaboration-table.component.ts, src/app/services/data/base-data.service.ts
=> Resolve bug where buttons were shown to register nodes wrongly

src/app/components/edit/user-edit/user-edit.component.ts
The issue was due to a wrong request to GET /role because the organization id was not known at that point in time
Fix #42
=> Fix bug where editing user hanged.

src/app/auth/services/user-permission.service.ts, src/app/components/edit/collaboration-edit/collaboration-edit.component.ts, src/app/components/edit/role-edit/role-edit.component.ts, src/app/components/edit/user-edit/user-edit.component.ts, src/app/components/organization/organization.component.ts, src/app/components/table/collaboration-table/collaboration-table.component.ts, src/app/components/table/node-table/node-table.component.ts, src/app/components/table/role-table/role-table.component.ts, src/app/components/table/task-table/task-table.component.ts, src/app/components/table/user-table/user-table.component.ts, src/app/components/view-single/collaboration-view-single/collaboration-view-single.component.ts, src/app/components/view-single/role-view-single/role-view-single.component.ts, src/app/components/view-single/user-view-single/user-view-single.component.ts, src/app/services/data/base-data.service.ts, src/app/services/data/collab-data.service.ts, src/app/services/data/node-data.service.ts, src/app/services/data/org-data.service.ts, src/app/services/data/result-data.service.ts, src/app/services/data/role-data.service.ts, src/app/services/data/rule-data.service.ts, src/app/services/data/task-data.service.ts, src/app/services/data/user-data.service.ts
…but rather use directly list of resources 
i.e. no longer using observables as they were not really useful here
Fix #44
=> In data services, no longer using observables of lists of resources

src/app/auth/services/user-permission.service.ts, src/app/services/common/sign-out.service.ts
So that when another user logs in after that, there is not a short period where some info of old user is still available
=> On logout, clear permissions of user from the userPermissionService

src/app/components/edit/user-edit/user-edit.component.html, src/app/components/edit/user-edit/user-edit.component.ts
=> Add checks for required fields in creating user

src/app/app.module.ts, src/app/components/edit/user-edit/change-password/change-password.component.html, src/app/components/edit/user-edit/change-password/change-password.component.scss, src/app/components/edit/user-edit/change-password/change-password.component.spec.ts, src/app/components/edit/user-edit/change-password/change-password.component.ts, src/app/components/edit/user-edit/user-edit.component.html, src/app/components/profile/profile.component.html, src/app/components/profile/profile.component.ts
=> Added option to change password on user edit page for the user that is logged in

src/app/components/table/base-table/table.component.ts, src/app/components/table/task-table/task-table.component.html, src/app/components/table/task-table/task-table.component.ts
=> Add functionality to refresh tasks on task page

package-lock.json, package.json, src/app/app-routing.module.ts, src/app/app.module.ts, src/app/auth/services/auth.service.ts, src/app/components/login/login-page/login-page.component.html, src/app/components/login/login/login.component.ts, src/app/components/login/mfa-code/mfa-code.component.html, src/app/components/login/mfa-code/mfa-code.component.spec.ts, src/app/components/login/mfa-code/mfa-code.component.ts, src/app/components/login/mfa-lost/mfa-lost.component.html, src/app/components/login/mfa-lost/mfa-lost.component.spec.ts, src/app/components/login/mfa-lost/mfa-lost.component.ts, src/app/components/login/mfa-recover/mfa-recover.component.html, src/app/components/login/mfa-recover/mfa-recover.component.spec.ts, src/app/components/login/mfa-recover/mfa-recover.component.ts, src/app/components/login/setup-mfa/setup-mfa.component.html, src/app/components/login/setup-mfa/setup-mfa.component.scss, src/app/components/login/setup-mfa/setup-mfa.component.spec.ts, src/app/components/login/setup-mfa/setup-mfa.component.ts
Added several views in the login pages to handle two-factor authentication:
- Added page to setup MFA by scanning QR code
- Added page to enter a six-digit TOTP code
- Added page to request an email to reset the MFA
- Added page to enter token from email to reset MFA and generate new QR code
=> Multi-factor authentication

src/app/components/organization/organization.component.html, src/app/components/organization/organization.component.ts
=> If user has no first and last name, show their username instead

src/app/auth/auth.interceptor.ts, src/app/components/table/task-table/task-table.component.ts, src/app/services/common/modal.service.ts, src/app/services/common/sign-out.service.ts
Previously, in that case the UI simply stopped working, requiring a refresh to go to the login page
=> When refresh token is not valid anymore, logout the user

src/app/components/edit/task-create/task-create.component.html, src/app/components/edit/task-create/task-create.component.ts, src/app/components/view/task-view/task-view.component.html, src/app/components/view/task-view/task-view.component.ts, src/app/interfaces/task.ts, src/app/services/api/task-api.service.ts, src/app/services/common/convert-json.service.ts
UI part of https://github.com/vantage6/vantage6/issues/440
=> Adapt UI to option in v4.0 that one task uses multiple databases

src/app/components/edit/task-create/task-create.component.ts, src/app/components/view/task-view/task-view.component.ts, src/app/services/api/task-api.service.ts
**To be merged only after JSON serialization is default on branch release/v4.0 in main repo**
=> For vantage server that only supports JSON serialization

src/app/components/navbar/navbar.component.scss
Fix double vertical scrollbar.
=> Fix double vertical scrollbar

new-frontend/.eslintrc.json, new-frontend/src/app/components/visualize-result/visualize-result.component.ts, new-frontend/src/app/models/api/task.models.ts, new-frontend/src/app/pages/task/read/task-read.component.html, new-frontend/src/app/pages/task/read/task-read.component.ts, new-frontend/src/app/services/file.service.ts, new-frontend/src/app/services/task.service.ts, new-frontend/src/assets/localizations/en.json
=> Display and download of task results

new-frontend/src/app/app.module.ts, new-frontend/src/app/components/role-form/role-form.component.html, new-frontend/src/app/components/role-form/role-form.component.ts, new-frontend/src/app/components/role-submit-buttons/role-submit-buttons.component.html, new-frontend/src/app/components/role-submit-buttons/role-submit-buttons.component.scss, new-frontend/src/app/components/role-submit-buttons/role-submit-buttons.component.ts, new-frontend/src/app/pages/role/read/role-read.component.html, new-frontend/src/app/pages/role/read/role-read.component.scss, new-frontend/src/app/pages/role/read/role-read.component.ts, new-frontend/src/assets/localizations/en.json
When no permission is selected:
Fixes #185
=> Make sure at least one rule is selected when creating or editing a role

new-frontend/src/app/models/api/task.models.ts, new-frontend/src/app/pages/task/list/task-list.component.ts
=> Don't show subtasks on page with task table

new-frontend/src/app/app-routing.module.ts, new-frontend/src/app/helpers/node.helper.ts, new-frontend/src/app/models/api/node.model.ts, new-frontend/src/app/models/api/task.models.ts, new-frontend/src/app/pages/task/create/steps/database-step/database-step.component.ts, new-frontend/src/app/pages/task/create/task-create.component.html, new-frontend/src/app/pages/task/create/task-create.component.ts, new-frontend/src/app/pages/task/read/task-read.component.html, new-frontend/src/app/pages/task/read/task-read.component.ts, new-frontend/src/app/routes.ts, new-frontend/src/assets/localizations/en.json
=> New frontend/feature/repeat task

new-frontend/src/app/app.module.ts, new-frontend/src/app/components/forms/user-form/user-form.component.html, new-frontend/src/app/components/forms/user-form/user-form.component.scss, new-frontend/src/app/components/forms/user-form/user-form.component.ts, new-frontend/src/app/components/permissions-matrix/permissions-matrix.component.html, new-frontend/src/app/components/permissions-matrix/permissions-matrix.component.scss, new-frontend/src/app/components/permissions-matrix/permissions-matrix.component.ts, new-frontend/src/app/models/api/role.model.ts, new-frontend/src/app/models/api/rule.model.ts, new-frontend/src/app/models/api/user.model.ts, new-frontend/src/app/pages/role/read/role-read.component.html, new-frontend/src/app/pages/user/edit/user-edit.component.ts, new-frontend/src/app/pages/user/read/user-read.component.html, new-frontend/src/app/pages/user/read/user-read.component.scss, new-frontend/src/app/pages/user/read/user-read.component.ts, new-frontend/src/app/services/rule.service.ts, new-frontend/src/app/services/user.service.ts, new-frontend/src/assets/localizations/en.json, new-frontend/src/environments/environment.development.ts
Only edit functionalty has been implemented. Permissions are not yet visible in view mode.
Resolves #184
=> Edit user specific permission rules.

new-frontend/src/app/helpers/task.helper.ts, new-frontend/src/app/models/api/task.models.ts, new-frontend/src/app/pages/task/read/task-read.component.html, new-frontend/src/app/pages/task/read/task-read.component.ts, new-frontend/src/app/services/task.service.ts, new-frontend/src/assets/localizations/en.json
=> Add functionality to kill tasks that are running/pending

new-frontend/src/app/components/table/table.component.html, new-frontend/src/app/components/table/table.component.scss, new-frontend/src/app/components/table/table.component.ts, new-frontend/src/app/helpers/api.helper.ts, new-frontend/src/app/helpers/general.helper.ts, new-frontend/src/app/models/api/collaboration.model.ts, new-frontend/src/app/models/api/organization.model.ts, new-frontend/src/app/models/api/role.model.ts, new-frontend/src/app/models/api/task.models.ts, new-frontend/src/app/models/api/user.model.ts, new-frontend/src/app/models/application/table.model.ts, new-frontend/src/app/models/constants/table.ts, new-frontend/src/app/pages/collaboration/list/collaboration-list.component.html, new-frontend/src/app/pages/collaboration/list/collaboration-list.component.ts, new-frontend/src/app/pages/organization/list/organization-list.component.html, new-frontend/src/app/pages/organization/list/organization-list.component.ts, new-frontend/src/app/pages/role/list/role-list.component.html, new-frontend/src/app/pages/role/list/role-list.component.ts, new-frontend/src/app/pages/task/list/task-list.component.html, new-frontend/src/app/pages/task/list/task-list.component.ts, new-frontend/src/app/pages/user/list/user-list.component.html, new-frontend/src/app/pages/user/list/user-list.component.ts, new-frontend/src/app/styles/config.scss, new-frontend/src/assets/localizations/en.json
Applied to role-list and user-list tables. If approved we can apply it to all tables where necessary.
=> Generic table search

src/app/models/api/task.models.ts, src/app/pages/task/create/task-create.component.html, src/app/pages/task/create/task-create.component.ts, src/app/pages/task/task.helper.ts, src/app/pages/template-task/create/template-task-create.component.ts
- sheet_name parameter was not properly passed to the server
- loading column names screen was not properly displayed
=> Fix issues with creating tasks

src/app/pages/task/create/steps/database-step/database-step.component.ts
=> No query field is necessary when executing task on an omop database

src/app/pages/task/create/steps/database-step/database-step.component.html, src/app/pages/task/create/steps/database-step/database-step.component.ts, src/app/pages/task/create/task-create.component.html, src/app/pages/task/create/task-create.component.scss, src/assets/localizations/en.json
Adds explanations to create task page
Fix #233
=> Added step-by-step explanations to create task page

src/app/pages/collaboration/list/collaboration-list.component.ts, src/app/pages/organization/list/organization-list.component.ts, src/app/pages/role/list/role-list.component.ts, src/app/pages/user/list/user-list.component.ts
=> Add ID column to table of organizations, collaboration, roles, and users
